# Generated by Django 5.2.11 on 2026-02-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_modul', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
