# Generated by Django 5.2.13 on 2026-05-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_modul', '0002_remove_order_coupon_delete_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cash',
            field=models.BooleanField(default=True),
        ),
    ]
