# Generated by Django 5.2.11 on 2026-03-19 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('order_modul', '0002_remove_order_coupon_delete_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='usd', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_payment',
            field=models.ForeignKey(blank=True, help_text="Agar bo'lib to'lash bo'lsa, qaysi oylik to'lovga tegishli", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_payments', to='order_modul.installmentpayment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
