# Generated by Django 5.2.13 on 2026-05-02 19:50

import billing.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_payment_options_payment_currency_and_more'),
        ('order_modul', '0002_remove_order_coupon_delete_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment_payment',
            field=models.ForeignKey(blank=True, help_text="Agar bo'lib to'lash bo'lsa, qaysi oylik to'lovga tegishli", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='order_modul.installmentpayment'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Karta raqamini kiriting (16 xonali)', max_length=19, validators=[billing.models.validate_card_number])),
                ('expiration_date', models.CharField(help_text='Format: MM/YY (masalan: 05/27)', validators=[billing.models.validate_expiry])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
