# Generated by Django 5.2.13 on 2026-05-02 19:58

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_card_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.CharField(help_text='Format: MM/YY (masalan: 05/27)', max_length=5, validators=[billing.models.validate_expiry]),
        ),
    ]
