# Generated by Django 5.2.13 on 2026-05-03 07:09

import billing.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_card_expiration_date'),
        ('order_modul', '0003_order_is_cash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='card',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Karta balansi (so'm)", max_digits=14),
        ),
        migrations.AddField(
            model_name='payment',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(help_text='16 xonali karta raqami', max_length=19, validators=[billing.models.validate_card_number]),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.CharField(help_text='Format: MM/YY', max_length=5, validators=[billing.models.validate_expiry]),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment_payment',
            field=models.ForeignKey(blank=True, help_text="Agar bu nasiyadan oylik to'lov bo'lsa", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='order_modul.installmentpayment'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
