# Generated by Django 5.2.11 on 2026-02-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_modul', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_stock',
        ),
    ]
