# Generated by Django 5.2.11 on 2026-02-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_modul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsellerrequest',
            name='review_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='review_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
